#!/usr/bin/env bash

if [[ -s "/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@depends" ]]
then
  source "/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@depends"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@depends'" >&2
  exit 1
fi
