#!/usr/bin/env bash

if [[ -s "/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@basic" ]]
then
  source "/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@basic"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/data/solo/ace/users/s/supersym/.rvm/environments/ruby-1.9.3-p327@basic'" >&2
  exit 1
fi
